# Use the official .NET 8 SDK image as the base image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

ENV ASPNETCORE_ENVIRONMENT=Development
# Set the working directory inside the container
WORKDIR /app

# Copy the project files into the container
COPY *.csproj ./

# Restore the project dependencies
RUN dotnet restore

# Copy the rest of the application code into the container
COPY . ./

# Build the application
RUN dotnet build -c Release -o out

# Use the runtime image to create the final image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

# Expose the port that the application will run on
EXPOSE 8080

# Optional: Health check to verify the application is running
HEALTHCHECK CMD curl --fail http://localhost:8080/ || exit 1

# Define the entry point for the application
ENTRYPOINT ["dotnet", "XmlaApi.dll"]
